version: "3.9"

# для каждого сервиса будет создан отдельный контейнер
services:
  # имя сервиса
  app:
    # путь к папке где лежит Dockerfile для создания образа
    build: ./app
    volumes:
      # если указать путь до папки в контейнере без ":", а ее нет на пк, то папка не будет удалена
      - /app/folder_we_dont_want_to_rewrite
      # содержимое из локальной папки заменит содержимое внутри папки контейнера
      - ./some_folder_on_pc:/app
    # добавить переменные окружения
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # указываем после каких контейнеров будет запускаться этот сервис, т.к он зависит от них.
    # depends_on не ожидает старта самого процесса, лишь указывает порядок запуска контейнеров
    depends_on:
      - db

  db:
    # какой образ использовать
    image: postgres:bookworm
    # всегда перезапускать контейнер, в случае завершения процесса
    restart: always
    # переменные окружения можно указать и как словарь, а не список как сверху
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # переброс портов
    ports:
      - "5432:5432"
    # создаем маппинг томов(в данном случае, созданную папку в докере с папкой в контейнере)
    volumes:
      - db_data:/var/lib/postgresql/data
# создаем папку для хранения данных на виртуальной машине докера
volumes:
  db_data:
